apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: speaker
    app.kubernetes.io/instance: ocf-metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-2.3.7
  name: ocf-metallb-pod-lister
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
