apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: hubble-ui
  name: hubble-ui
  namespace: cilium
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8081
  selector:
    k8s-app: hubble-ui
  type: ClusterIP
