apiVersion: v1
data:
  envoy.yaml: "static_resources:\n  listeners:\n    - name: listener_hubble_ui\n \
    \     address:\n        socket_address:\n          address: 0.0.0.0\n        \
    \  port_value: 8081\n      filter_chains:\n        - filters:\n            - name:\
    \ envoy.filters.network.http_connection_manager\n              typed_config:\n\
    \                \"@type\": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager\n\
    \                codec_type: auto\n                stat_prefix: ingress_http\n\
    \                route_config:\n                  name: local_route\n        \
    \          virtual_hosts:\n                    - name: local_service\n       \
    \               domains: [\"*\"]\n                      routes:\n            \
    \            - match:\n                            prefix: \"/api/\"\n       \
    \                   route:\n                            cluster: backend\n   \
    \                         prefix_rewrite: \"/\"\n                            timeout:\
    \ 0s\n                            max_stream_duration:\n                     \
    \         grpc_timeout_header_max: 0s\n                        - match:\n    \
    \                        prefix: \"/\"\n                          route:\n   \
    \                         cluster: frontend\n                      cors:\n   \
    \                     allow_origin_string_match:\n                          -\
    \ prefix: \"*\"\n                        allow_methods: GET, PUT, DELETE, POST,\
    \ OPTIONS\n                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout\n\
    \                        max_age: \"1728000\"\n                        expose_headers:\
    \ grpc-status,grpc-message\n                http_filters:\n                  -\
    \ name: envoy.filters.http.grpc_web\n                  - name: envoy.filters.http.cors\n\
    \                  - name: envoy.filters.http.router\n  clusters:\n    - name:\
    \ frontend\n      connect_timeout: 0.25s\n      type: strict_dns\n      lb_policy:\
    \ round_robin\n      load_assignment:\n        cluster_name: frontend\n      \
    \  endpoints:\n          - lb_endpoints:\n              - endpoint:\n        \
    \          address:\n                    socket_address:\n                   \
    \   address: 127.0.0.1\n                      port_value: 8080\n    - name: backend\n\
    \      connect_timeout: 0.25s\n      type: logical_dns\n      lb_policy: round_robin\n\
    \      http2_protocol_options: {}\n      load_assignment:\n        cluster_name:\
    \ backend\n        endpoints:\n          - lb_endpoints:\n              - endpoint:\n\
    \                  address:\n                    socket_address:\n           \
    \           address: 127.0.0.1\n                      port_value: 8090\n"
kind: ConfigMap
metadata:
  name: hubble-ui-envoy
  namespace: cilium
