apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-stack-admission-create
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 16.0.1
    chart: kube-prometheus-stack-16.0.1
    heritage: Helm
    release: ocf-prometheus
  name: ocf-prometheus-kube-promet-admission-create
  namespace: prometheus
spec:
  template:
    metadata:
      labels:
        app: kube-prometheus-stack-admission-create
        app.kubernetes.io/instance: ocf-prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 16.0.1
        chart: kube-prometheus-stack-16.0.1
        heritage: Helm
        release: ocf-prometheus
      name: ocf-prometheus-kube-promet-admission-create
    spec:
      containers:
      - args:
        - create
        - --host=ocf-prometheus-kube-promet-operator,ocf-prometheus-kube-promet-operator.prometheus.svc
        - --namespace=prometheus
        - --secret-name=ocf-prometheus-kube-promet-admission
        image: jettech/kube-webhook-certgen:v1.5.0
        imagePullPolicy: IfNotPresent
        name: create
        resources: {}
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: ocf-prometheus-kube-promet-admission
