apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 16.0.1
    chart: kube-prometheus-stack-16.0.1
    heritage: Helm
    release: ocf-prometheus
    self-monitor: 'true'
  name: ocf-prometheus-kube-promet-alertmanager
  namespace: prometheus
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: ocf-prometheus-kube-promet-alertmanager
    app: alertmanager
  type: ClusterIP
