apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.5.5
    helm.sh/chart: grafana-6.9.1
  name: ocf-prometheus-grafana-test
  namespace: prometheus
spec:
  containers:
  - command:
    - /opt/bats/bin/bats
    - -t
    - /tests/run.sh
    image: bats/bats:v1.1.0
    imagePullPolicy: IfNotPresent
    name: ocf-prometheus-test
    volumeMounts:
    - mountPath: /tests
      name: tests
      readOnly: true
  restartPolicy: Never
  serviceAccountName: ocf-prometheus-grafana-test
  volumes:
  - configMap:
      name: ocf-prometheus-grafana-test
    name: tests
