apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 16.0.1
    chart: kube-prometheus-stack-16.0.1
    heritage: Helm
    release: ocf-prometheus
  name: ocf-prometheus-kube-promet-alertmanager
  namespace: prometheus
rules:
- apiGroups:
  - policy
  resourceNames:
  - ocf-prometheus-kube-promet-alertmanager
  resources:
  - podsecuritypolicies
  verbs:
  - use
