apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.5.5
    helm.sh/chart: grafana-6.9.1
  name: ocf-prometheus-grafana
  namespace: prometheus
rules:
- apiGroups:
  - extensions
  resourceNames:
  - ocf-prometheus-grafana
  resources:
  - podsecuritypolicies
  verbs:
  - use
