apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 16.0.1
    chart: kube-prometheus-stack-16.0.1
    heritage: Helm
    release: ocf-prometheus
  name: ocf-prometheus-kube-promet-kubernetes-resources
  namespace: prometheus
spec:
  groups:
  - name: kubernetes-resources
    rules:
    - alert: KubeCPUOvercommit
      annotations:
        description: Cluster has overcommitted CPU resource requests for Pods and
          cannot tolerate node failure.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuovercommit
        summary: Cluster has overcommitted CPU resource requests.
      expr: "sum(namespace_cpu:kube_pod_container_resource_requests:sum{})\n  /\n\
        sum(kube_node_status_allocatable{resource=\"cpu\"})\n  >\n((count(kube_node_status_allocatable{resource=\"\
        cpu\"}) > 1) - 1) / count(kube_node_status_allocatable{resource=\"cpu\"})"
      for: 5m
      labels:
        severity: warning
    - alert: KubeMemoryOvercommit
      annotations:
        description: Cluster has overcommitted memory resource requests for Pods and
          cannot tolerate node failure.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubememoryovercommit
        summary: Cluster has overcommitted memory resource requests.
      expr: "sum(namespace_memory:kube_pod_container_resource_requests:sum{})\n  /\n\
        sum(kube_node_status_allocatable{resource=\"memory\"})\n  >\n((count(kube_node_status_allocatable{resource=\"\
        memory\"}) > 1) - 1)\n  /\ncount(kube_node_status_allocatable{resource=\"\
        memory\"})"
      for: 5m
      labels:
        severity: warning
    - alert: KubeCPUQuotaOvercommit
      annotations:
        description: Cluster has overcommitted CPU resource requests for Namespaces.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuquotaovercommit
        summary: Cluster has overcommitted CPU resource requests.
      expr: "sum(kube_resourcequota{job=\"kube-state-metrics\", type=\"hard\", resource=\"\
        cpu\"})\n  /\nsum(kube_node_status_allocatable{resource=\"cpu\"})\n  > 1.5"
      for: 5m
      labels:
        severity: warning
    - alert: KubeMemoryQuotaOvercommit
      annotations:
        description: Cluster has overcommitted memory resource requests for Namespaces.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubememoryquotaovercommit
        summary: Cluster has overcommitted memory resource requests.
      expr: "sum(kube_resourcequota{job=\"kube-state-metrics\", type=\"hard\", resource=\"\
        memory\"})\n  /\nsum(kube_node_status_allocatable{resource=\"memory\",job=\"\
        kube-state-metrics\"})\n  > 1.5"
      for: 5m
      labels:
        severity: warning
    - alert: KubeQuotaAlmostFull
      annotations:
        description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage
          }} of its {{ $labels.resource }} quota.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaalmostfull
        summary: Namespace quota is going to be full.
      expr: "kube_resourcequota{job=\"kube-state-metrics\", type=\"used\"}\n  / ignoring(instance,\
        \ job, type)\n(kube_resourcequota{job=\"kube-state-metrics\", type=\"hard\"\
        } > 0)\n  > 0.9 < 1"
      for: 15m
      labels:
        severity: info
    - alert: KubeQuotaFullyUsed
      annotations:
        description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage
          }} of its {{ $labels.resource }} quota.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotafullyused
        summary: Namespace quota is fully used.
      expr: "kube_resourcequota{job=\"kube-state-metrics\", type=\"used\"}\n  / ignoring(instance,\
        \ job, type)\n(kube_resourcequota{job=\"kube-state-metrics\", type=\"hard\"\
        } > 0)\n  == 1"
      for: 15m
      labels:
        severity: info
    - alert: KubeQuotaExceeded
      annotations:
        description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage
          }} of its {{ $labels.resource }} quota.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaexceeded
        summary: Namespace quota has exceeded the limits.
      expr: "kube_resourcequota{job=\"kube-state-metrics\", type=\"used\"}\n  / ignoring(instance,\
        \ job, type)\n(kube_resourcequota{job=\"kube-state-metrics\", type=\"hard\"\
        } > 0)\n  > 1"
      for: 15m
      labels:
        severity: warning
    - alert: CPUThrottlingHigh
      annotations:
        description: '{{ $value | humanizePercentage }} throttling of CPU in namespace
          {{ $labels.namespace }} for container {{ $labels.container }} in pod {{
          $labels.pod }}.'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-cputhrottlinghigh
        summary: Processes experience elevated CPU throttling.
      expr: "sum(increase(container_cpu_cfs_throttled_periods_total{container!=\"\"\
        , }[5m])) by (container, pod, namespace)\n  /\nsum(increase(container_cpu_cfs_periods_total{}[5m]))\
        \ by (container, pod, namespace)\n  > ( 25 / 100 )"
      for: 15m
      labels:
        severity: info
