apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.5.5
    helm.sh/chart: grafana-6.9.1
  name: ocf-prometheus-grafana
  namespace: prometheus
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/name: grafana
  type: ClusterIP
