apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  name: tekton-pipelines-info
  namespace: tekton-pipelines
rules:
- apiGroups:
  - ''
  resourceNames:
  - pipelines-info
  resources:
  - configmaps
  verbs:
  - get
