apiVersion: v1
data:
  redis_liveness.sh: "response=$(\n  redis-cli \\\n    -h localhost \\\n    -p 6379\
    \ \\\n    ping\n)\nif [ \"$response\" != \"PONG\" ] && [ \"${response:0:7}\" !=\
    \ \"LOADING\" ] ; then\n  echo \"$response\"\n  exit 1\nfi\necho \"response=$response\"\
    \n"
  redis_readiness.sh: "response=$(\n  redis-cli \\\n    -h localhost \\\n    -p 6379\
    \ \\\n    ping\n)\nif [ \"$response\" != \"PONG\" ] ; then\n  echo \"$response\"\
    \n  exit 1\nfi\necho \"response=$response\"\n"
  sentinel_liveness.sh: "response=$(\n  redis-cli \\\n    -h localhost \\\n    -p\
    \ 26379 \\\n    ping\n)\nif [ \"$response\" != \"PONG\" ]; then\n  echo \"$response\"\
    \n  exit 1\nfi\necho \"response=$response\"\n"
kind: ConfigMap
metadata:
  labels:
    app: argocd-redis-ha
    chart: redis-ha-4.12.15
    heritage: Helm
    release: argocd
  name: argocd-redis-ha-health-configmap
