apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: redis-ha
    chart: redis-ha-4.12.15
    component: argocd-redis-ha-haproxy
    heritage: Helm
    release: argocd
  name: argocd-redis-ha-haproxy
rules:
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - get
