apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
spec:
  keys: []
  path: pwned/argocd/argocd-secret
  type: Opaque
