apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: ocf-contour
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-4.3.4
  name: ocf-contour
  namespace: contour
spec:
  ports:
  - name: xds
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: ocf-contour
    app.kubernetes.io/name: contour
  type: ClusterIP
