apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ocf-contour
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-4.3.4
  name: ocf-contour-contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocf-contour-contour
subjects:
- kind: ServiceAccount
  name: ocf-contour-contour
  namespace: contour
