apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: ocf-contour
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-4.3.4
  name: ocf-contour-contour
  namespace: contour
