apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: '1'
  labels:
    app.kubernetes.io/component: contour-certgen
    app.kubernetes.io/instance: ocf-contour
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-4.3.4
  name: ocf-contour-contour-certgen
  namespace: contour
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: contour-certgen
        app.kubernetes.io/instance: ocf-contour
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: contour
        helm.sh/chart: contour-4.3.4
    spec:
      containers:
      - args:
        - certgen
        - --kube
        - --incluster
        - --overwrite
        - --secrets-format=compact
        - --namespace=$(CONTOUR_NAMESPACE)
        command:
        - contour
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: docker.io/bitnami/contour:1.15.1-debian-10-r9
        imagePullPolicy: IfNotPresent
        name: contour
        resources:
          limits: {}
          requests: {}
      restartPolicy: Never
      securityContext:
        fsGroup: null
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccountName: ocf-contour-contour-certgen
  ttlSecondsAfterFinished: 0
