apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: ocf-contour
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-4.3.4
  name: ocf-contour-contour
  namespace: contour
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: contour
      app.kubernetes.io/instance: ocf-contour
      app.kubernetes.io/name: contour
  strategy:
    rollingUpdate:
      maxSurge: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: add045f75e1a39bd2306e75d2c0bff6029985b5002fe99904e9cd767fc8b2e4b
      labels:
        app.kubernetes.io/component: contour
        app.kubernetes.io/instance: ocf-contour
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: contour
        helm.sh/chart: contour-4.3.4
    spec:
      affinity:
        nodeAffinity: null
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: contour
                  app.kubernetes.io/instance: ocf-contour
                  app.kubernetes.io/name: contour
              namespaces:
              - contour
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - args:
        - serve
        - --incluster
        - --xds-address=0.0.0.0
        - --xds-port=8001
        - --envoy-service-http-port=80
        - --envoy-service-https-port=443
        - --contour-cafile=/certs/ca.crt
        - --contour-cert-file=/certs/tls.crt
        - --contour-key-file=/certs/tls.key
        - --config-path=/config/contour.yaml
        command:
        - contour
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: docker.io/bitnami/contour:1.15.1-debian-10-r9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: contour
        ports:
        - containerPort: 8001
          name: xds
          protocol: TCP
        - containerPort: 8000
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8001
          timeoutSeconds: 5
        resources:
          limits: {}
          requests: {}
        volumeMounts:
        - mountPath: /certs
          name: contourcert
          readOnly: true
        - mountPath: /config
          name: contour-config
          readOnly: true
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: null
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccountName: ocf-contour-contour
      volumes:
      - name: contourcert
        secret:
          secretName: contourcert
      - configMap:
          defaultMode: 420
          items:
          - key: contour.yaml
            path: contour.yaml
          name: ocf-contour
        name: contour-config
