apiVersion: v1
data:
  contour.yaml: "accesslog-format: envoy\ndisablePermitInsecure: false\nenvoy-service-name:\
    \ 'ocf-contour-envoy'\nleaderelection:\n  configmap-namespace: 'contour'\ntls:\n\
    \  fallback-certificate: null\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: contour
    app.kubernetes.io/instance: ocf-contour
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-4.3.4
  name: ocf-contour
  namespace: contour
