apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-notary-signer
spec:
  ports:
  - name: notary-signer
    port: 7899
    targetPort: notary-signer
  selector:
    app.kubernetes.io/component: notary-signer
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/name: harbor
