apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-registry
spec:
  ports:
  - name: registry
    port: 5000
  - name: controller
    port: 8080
  selector:
    app.kubernetes.io/component: registry
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/name: harbor
