apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.4.6
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
  name: ocf-harbor-postgresql-headless
  namespace: harbor
spec:
  clusterIP: None
  ports:
  - name: tcp-postgresql
    port: 5432
    targetPort: tcp-postgresql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/name: postgresql
  type: ClusterIP
