apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: trivy
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-trivy
spec:
  ports:
  - name: api-server
    port: 8080
    protocol: TCP
    targetPort: api-server
  selector:
    app.kubernetes.io/component: trivy
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/name: harbor
