apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-core
spec:
  keys:
  - secretKey
  - secret
  - tls.crt
  - tls.key
  path: pwned/harbor/ocf-harbor-core
  type: Opaque
