apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-core-envvars
spec:
  keys:
  - _REDIS_URL_CORE
  - _REDIS_URL_REG
  - REGISTRY_CREDENTIAL_USERNAME
  - REGISTRY_CREDENTIAL_PASSWORD
  - CSRF_KEY
  - HARBOR_ADMIN_PASSWORD
  - POSTGRESQL_PASSWORD
  path: pwned/harbor/ocf-harbor-core-envvars
  type: Opaque
