apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  labels:
    app.kubernetes.io/component: trivy
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-trivy-envvars
spec:
  keys:
  - SCANNER_TRIVY_GITHUB_TOKEN
  - SCANNER_REDIS_URL
  - SCANNER_STORE_REDIS_URL
  - SCANNER_JOB_QUEUE_REDIS_URL
  path: pwned/harbor/ocf-harbor-trivy-envvars
  type: Opaque
