apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-notary-server
spec:
  ports:
  - name: notary-server
    port: 4443
    targetPort: notary-server
  selector:
    app.kubernetes.io/component: notary-server
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/name: harbor
