apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-14.2.0
  name: ocf-harbor-redis-headless
  namespace: harbor
spec:
  clusterIP: None
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/name: redis
  type: ClusterIP
