apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-portal
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/component: portal
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/name: harbor
