apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: trivy
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-trivy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: trivy
      app.kubernetes.io/instance: ocf-harbor
      app.kubernetes.io/name: harbor
  serviceName: ocf-harbor-trivy
  template:
    metadata:
      annotations:
        checksum/configmap-env: cd7efefdfa1d39195c8e4fe6791675b1943ed31ac9fdf668ea0767181bc145f5
        checksum/secret-env: 3b9c37a7e3e06ea4cb65cc5920e672d422b13bb23696e3b88a16ce287f581a2d
      labels:
        app.kubernetes.io/component: trivy
        app.kubernetes.io/instance: ocf-harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: harbor
        helm.sh/chart: harbor-10.0.4
    spec:
      affinity:
        nodeAffinity: null
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: trivy
                  app.kubernetes.io/instance: ocf-harbor
                  app.kubernetes.io/name: harbor
              namespaces:
              - harbor
              topologyKey: kubernetes.io/hostname
            weight: 1
      automountServiceAccountToken: false
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: 'false'
        envFrom:
        - configMapRef:
            name: ocf-harbor-trivy-envvars
        - secretRef:
            name: ocf-harbor-trivy-envvars
        image: docker.io/bitnami/harbor-adapter-trivy:2.2.2-debian-10-r2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /probe/healthy
            port: api-server
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: trivy
        ports:
        - containerPort: 8080
          name: api-server
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /probe/ready
            port: api-server
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - mountPath: /bitnami/harbor-adapter-trivy/.cache
          name: data
          readOnly: false
      initContainers: null
      securityContext:
        fsGroup: 1001
      volumes: null
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        app.kubernetes.io/instance: ocf-harbor
        app.kubernetes.io/name: harbor
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
