apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: repo-server
  name: argocd-repo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      containers:
        - name: argocd-repo-server
          volumeMounts:
          - mountPath: /usr/local/sbin
            name: usr-local-bin
          - mountPath: /usr/local/include
            name: usr-local-include
          - mountPath: /usr/local/lib
            name: usr-local-lib
          env:
          - name: LD_LIBRARY_PATH
            value: /usr/local/lib
      volumes:
      - name: usr-local-lib
        emptyDir: {}
      - name: usr-local-include
        emptyDir: {}
      - name: usr-local-bin
        emptyDir: {}
      initContainers:
      - name: python
        image: python:3.9-buster
        command: ["sh", "-c"]
        args:
        - cp -r /usr/local/bin/. /mnt/usr/local/bin/ &&
          cp -r /usr/local/include/. /mnt/usr/local/include/ &&
          cp -r /usr/local/lib/. /mnt/usr/local/lib/
        volumeMounts:
        - mountPath: /mnt/usr/local/bin
          name: usr-local-bin
        - mountPath: /mnt/usr/local/include
          name: usr-local-include
        - mountPath: /mnt/usr/local/lib
          name: usr-local-lib
