apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: ocf-cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webhook
    helm.sh/chart: cert-manager-v1.1.0
  name: ocf-cert-manager-webhook:dynamic-serving
  namespace: cert-manager
rules:
- apiGroups:
  - ''
  resourceNames:
  - ocf-cert-manager-webhook-ca
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
