apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: fission-core-1.12.0
    svc: executor
  name: executor
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: executor
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        svc: executor
    spec:
      containers:
      - args:
        - --executorPort
        - '8888'
        - --namespace
        - fission-function
        command:
        - /fission-bundle
        env:
        - name: FETCHER_IMAGE
          value: fission/fetcher:1.12.0
        - name: RUNTIME_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: FETCHER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: ''
        - name: TRACING_SAMPLING_RATE
          value: '0.5'
        - name: ADOPT_EXISTING_RESOURCES
          value: 'false'
        - name: POD_READY_TIMEOUT
          value: 300s
        - name: ENABLE_ISTIO
          value: 'false'
        - name: FETCHER_MINCPU
          value: 10m
        - name: FETCHER_MINMEM
          value: 16Mi
        - name: FETCHER_MAXCPU
          value: ''
        - name: FETCHER_MAXMEM
          value: ''
        image: index.docker.io/fission/fission-bundle:1.12.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 35
          periodSeconds: 5
        name: executor
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8888
          name: http
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 1
          periodSeconds: 1
      serviceAccountName: fission-svc
