apiVersion: v1
kind: Service
metadata:
  labels:
    chart: fission-core-1.12.0
    svc: executor
  name: executor
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    svc: executor
  type: ClusterIP
