apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fission-storage
    chart: fission-core-1.12.0
    release: ocf-fission
  name: fission-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
