apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fission-admin
  namespace: fission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: fission-svc
  namespace: fission
