apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: fission-core-1.12.0
    svc: kubewatcher
  name: kubewatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: kubewatcher
  template:
    metadata:
      labels:
        svc: kubewatcher
    spec:
      containers:
      - args:
        - --kubewatcher
        - --routerUrl
        - http://router.fission
        command:
        - /fission-bundle
        env:
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: ''
        - name: TRACING_SAMPLING_RATE
          value: '0.5'
        image: index.docker.io/fission/fission-bundle:1.12.0
        imagePullPolicy: IfNotPresent
        name: kubewatcher
      serviceAccountName: fission-svc
