apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: fission-core
    chart: fission-core-1.12.0
    release: ocf-fission
  name: ocf-fission-fission-core-1.12.0-337
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: fission-core
        release: ocf-fission
      name: ocf-fission-fission-core
    spec:
      containers:
      - args:
        - --fn-pod-namespace
        - fission-function
        - --envbuilder-namespace
        - fission-builder
        command:
        - /pre-upgrade-checks
        image: fission/pre-upgrade-checks:1.12.0
        imagePullPolicy: IfNotPresent
        name: pre-upgrade-job
      restartPolicy: Never
      serviceAccountName: fission-svc
