apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: fission-router
    chart: fission-core-1.12.0
    svc: router
  name: router
spec:
  replicas: 1
  selector:
    matchLabels:
      application: fission-router
      svc: router
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        application: fission-router
        svc: router
    spec:
      containers:
      - args:
        - --routerPort
        - '8888'
        - --executorUrl
        - http://executor.fission
        command:
        - /fission-bundle
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROUTER_ROUND_TRIP_TIMEOUT
          value: 50ms
        - name: ROUTER_ROUNDTRIP_TIMEOUT_EXPONENT
          value: '2'
        - name: ROUTER_ROUND_TRIP_KEEP_ALIVE_TIME
          value: 30s
        - name: ROUTER_ROUND_TRIP_DISABLE_KEEP_ALIVE
          value: 'true'
        - name: ROUTER_ROUND_TRIP_MAX_RETRIES
          value: '10'
        - name: ROUTER_SVC_ADDRESS_MAX_RETRIES
          value: '5'
        - name: ROUTER_SVC_ADDRESS_UPDATE_TIMEOUT
          value: 30s
        - name: ROUTER_UNTAP_SERVICE_TIMEOUT
          value: 3600s
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: ''
        - name: TRACING_SAMPLING_RATE
          value: '0.5'
        - name: USE_ENCODED_PATH
          value: 'false'
        - name: DEBUG_ENV
          value: 'false'
        - name: DISPLAY_ACCESS_LOG
          value: 'false'
        image: index.docker.io/fission/fission-bundle:1.12.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /router-healthz
            port: 8888
          initialDelaySeconds: 35
          periodSeconds: 5
        name: router
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8888
          name: http
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /router-healthz
            port: 8888
          initialDelaySeconds: 1
          periodSeconds: 1
      serviceAccountName: fission-svc
