apiVersion: v1
kind: Service
metadata:
  labels:
    application: fission-router
    chart: fission-core-1.12.0
    svc: router
  name: router
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    svc: router
  type: ClusterIP
