apiVersion: v1
kind: Service
metadata:
  labels:
    application: fission-storage
    chart: fission-core-1.12.0
    svc: storagesvc
  name: storagesvc
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    svc: storagesvc
  type: ClusterIP
