apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: fission-core-1.12.0
    svc: timer
  name: timer
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: timer
  template:
    metadata:
      labels:
        svc: timer
    spec:
      containers:
      - args:
        - --timer
        - --routerUrl
        - http://router.fission
        command:
        - /fission-bundle
        env:
        - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
          value: ''
        - name: TRACING_SAMPLING_RATE
          value: '0.5'
        image: index.docker.io/fission/fission-bundle:1.12.0
        imagePullPolicy: IfNotPresent
        name: timer
      serviceAccountName: fission-svc
