apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    operator: rook
    storage-backend: ceph
  name: rook-ceph-object-bucket
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - objectbucket.io
  resources:
  - '*'
  verbs:
  - '*'
