apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-ceph-mgr
  namespace: rook
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - pods/log
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ceph.rook.io
  resources:
  - '*'
  verbs:
  - '*'
