apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rook-ceph-admission-controller-role
rules:
- apiGroups:
  - ceph.rook.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
