apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-ceph-cmd-reporter
  namespace: rook
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
