apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.0.1

# BOOTSTRAP: Circular dependency w/ Traefik
resources:
- resources/argocd-server-http-ingress.yaml
# BOOTSTRAP: Circular dependency w/ Vault
#- resources/argocd-vault-secret.yaml

patchesStrategicMerge:
- overlays/argo-cd-cm.yaml
- overlays/argocd-rbac-cm.yaml
- overlays/argocd-server.yaml
- overlays/argocd-repo-server.yaml
# BOOTSTRAP: Circular dependency w/ Vault
#- overlays/argocd-secret.yaml

namespace: argocd
