apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app.kubernetes.io/component: pgpool
    app.kubernetes.io/instance: ocf-postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-7.5.2
  name: ocf-postgresql-postgresql-ha-pgpool
spec:
  ports:
  - name: postgresql
    nodePort: null
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app.kubernetes.io/component: pgpool
    app.kubernetes.io/instance: ocf-postgresql
    app.kubernetes.io/name: postgresql-ha
  sessionAffinity: None
  type: ClusterIP
