apiVersion: v1
data:
  pre-stop.sh: "#!/bin/bash\nset -o errexit\nset -o pipefail\nset -o nounset\n\n#\
    \ Debug section\nexec 3>&1\nexec 4>&2\n\n# Load Libraries\n. /opt/bitnami/scripts/liblog.sh\n\
    . /opt/bitnami/scripts/libpostgresql.sh\n. /opt/bitnami/scripts/librepmgr.sh\n\
    \n# Auxiliary functions\nis_new_primary_ready() {\n    return_value=1\n    currenty_primary_node=\"\
    $(repmgr_get_primary_node)\"\n    currenty_primary_host=\"$(echo $currenty_primary_node\
    \ | awk '{print $1}')\"\n\n    info \"$currenty_primary_host != $REPMGR_NODE_NETWORK_NAME\"\
    \n    if [[ $(echo $currenty_primary_node | wc -w) -eq 2 ]] && [[ \"$currenty_primary_host\"\
    \ != \"$REPMGR_NODE_NETWORK_NAME\" ]]; then\n        info \"New primary detected,\
    \ leaving the cluster...\"\n        return_value=0\n    else\n        info \"\
    Waiting for a new primary to be available...\"\n    fi\n    return $return_value\n\
    }\n\nexport MODULE=\"pre-stop-hook\"\n\nif [[ \"${BITNAMI_DEBUG}\" == \"true\"\
    \ ]]; then\n    info \"Bash debug is on\"\nelse\n    info \"Bash debug is off\"\
    \n    exec 1>/dev/null\n    exec 2>/dev/null\nfi\n\n# Load PostgreSQL & repmgr\
    \ environment variables\n. /opt/bitnami/scripts/postgresql-env.sh\n\npostgresql_enable_nss_wrapper\n\
    \n# Prepare env vars for managing roles\nprimary_node=\"$(repmgr_get_primary_node)\"\
    \nprimary_host=\"$(echo $primary_node | awk '{print $1}')\"\n\n# Stop postgresql\
    \ for graceful exit.\npostgresql_stop\n\nif [[ \"$primary_host\" == \"$REPMGR_NODE_NETWORK_NAME\"\
    \ ]]; then\n    info \"Primary node need to wait for a new primary node before\
    \ leaving the cluster\"\n    retry_while is_new_primary_ready 10 5\nelse\n   \
    \ info \"Standby node doesn't need to wait, leaving the cluster.\"\nfi"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: ocf-postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-7.5.2
  name: ocf-postgresql-postgresql-ha-postgresql-hooks-scripts
