apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ocf-postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-7.5.2
  name: ocf-postgresql-postgresql-ha-postgresql-headless
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: ocf-postgresql
    app.kubernetes.io/name: postgresql-ha
  type: ClusterIP
