apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ocf-eck-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: eck-operator-1.8.0
  name: elastic-operator
  namespace: eck-operator
