apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  labels:
    app.kubernetes.io/instance: ocf-eck-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: eck-operator-1.8.0
  name: elastic-operator-webhook-cert
  namespace: eck-operator
spec:
  keys: []
  path: pwned/eck-operator/elastic-operator-webhook-cert
  type: Opaque
